#! /usr/bin/env python

from PyQt4 import QtCore, QtGui, QtNetwork


class Server(QtNetwork.QTcpServer):
	def __init__(self, parent=None):
		super(Server, self).__init__(parent)
		
		self.newConnection.connect(self.handle_new_connection)
		self.listen(port=8922)

	def handle_new_connection(self):
		print "new connection!"
		connection = self.nextPendingConnection()
		connection.close()


if __name__ == '__main__':
	import sys
	app = QtGui.QApplication(sys.argv)
	server = Server()
	sys.exit(app.exec_())

