#! /usr/bin/env python

from PyQt4 import QtCore, QtGui, QtNetwork


class Server(QtNetwork.QTcpServer):
	def __init__(self, parent=None):
		super(Server, self).__init__(parent)
		
		self.newConnection.connect(self.new_connection)
		self.listen(port=8922)

	def new_connection(self):
		print "new connection!"


if __name__ == '__main__':
	import sys
	server = Server()
	app = QtGui.QApplication(sys.argv)
	sys.exit(app.exec_())

